export enum MemoryCategory {
  SCIENCE = 'SCIENCE', POLITICS = 'POLITICS', CULTURE = 'CULTURE',
  FAMILY = 'FAMILY', TECHNOLOGY = 'TECHNOLOGY', ART = 'ART',
  NATURE = 'NATURE', RELIGION = 'RELIGION', PHILOSOPHY = 'PHILOSOPHY',
  WAR = 'WAR', ECONOMICS = 'ECONOMICS', EDUCATION = 'EDUCATION',
  EXPLORATION = 'EXPLORATION', MEDICINE = 'MEDICINE',
}

export enum MemoryRarity { COMMON = 'COMMON', UNCOMMON = 'UNCOMMON', RARE = 'RARE', LEGENDARY = 'LEGENDARY' }

export enum MemoryDifficulty { LEVEL_1 = 1, LEVEL_2 = 2, LEVEL_3 = 3, LEVEL_4 = 4, LEVEL_5 = 5 }

export enum DecisionWeight { LOW = 'LOW', MEDIUM = 'MEDIUM', HIGH = 'HIGH', CRITICAL = 'CRITICAL' }

export enum EvidenceTier { SURFACE = 'SURFACE', CONTEXT = 'CONTEXT', COMPLICATION = 'COMPLICATION', REVELATION = 'REVELATION' }

export enum EvidenceSource {
  NEWS_REPORT = 'NEWS_REPORT', PERSONAL_DIARY = 'PERSONAL_DIARY',
  SCIENTIFIC_RECORD = 'SCIENTIFIC_RECORD', GOVERNMENT_DOCUMENT = 'GOVERNMENT_DOCUMENT',
  AUDIO_LOG = 'AUDIO_LOG', IMAGE = 'IMAGE', LETTER = 'LETTER'
}

export enum ContradictionType { FACTUAL = 'FACTUAL', MORAL = 'MORAL', POLITICAL = 'POLITICAL', SCIENTIFIC = 'SCIENTIFIC', HISTORICAL = 'HISTORICAL', CULTURAL = 'CULTURAL', RELIGIOUS = 'RELIGIOUS', TECHNOLOGICAL = 'TECHNOLOGICAL' }

export enum CorruptionType {
  MISSING_DATA = 'MISSING_DATA', PARTIAL_RECORD = 'PARTIAL_RECORD',
  TIMESTAMP_CONFLICT = 'TIMESTAMP_CONFLICT', SOURCE_LOSS = 'SOURCE_LOSS',
  RECONSTRUCTION = 'RECONSTRUCTION', UNKNOWN_AUTHOR = 'UNKNOWN_AUTHOR',
  ALTERED_RECORD = 'ALTERED_RECORD', PROPAGANDA = 'PROPAGANDA',
  DUPLICATE_NARRATIVE = 'DUPLICATE_NARRATIVE', FALSE_ATTRIBUTION = 'FALSE_ATTRIBUTION',
}

export enum DecisionType { PRESERVE = 'PRESERVE', DISCARD = 'DISCARD' }

export enum SessionStatus { ACTIVE = 'ACTIVE', LOW_POWER = 'LOW_POWER', FINALIZING = 'FINALIZING', COMPLETED = 'COMPLETED', ABANDONED = 'ABANDONED' }

export enum NarrativePhase { INTRODUCTION = 'INTRODUCTION', DISCOVERY = 'DISCOVERY', CONFLICT = 'CONFLICT', CRISIS = 'CRISIS', RESOLUTION = 'RESOLUTION' }

export enum GameState { BOOT = 'BOOT', INTRO = 'INTRO', ARCHIVE = 'ARCHIVE', MEMORY = 'MEMORY', INVESTIGATION = 'INVESTIGATION', CORRUPTED = 'CORRUPTED', TRANSITION = 'TRANSITION', FINALIZATION = 'FINALIZATION', ENDING = 'ENDING', HISTORY_BOOK = 'HISTORY_BOOK', COMPLETE = 'COMPLETE' }

export enum RelationType { SUPPORTS = 'SUPPORTS', CONTRADICTS = 'CONTRADICTS', EXPLAINS = 'EXPLAINS', EXPANDS = 'EXPANDS', QUESTIONS = 'QUESTIONS', CONSEQUENCE_OF = 'CONSEQUENCE_OF' }

export enum GovernmentType { TECHNOCRACY = 'TECHNOCRACY', DEMOCRACY = 'DEMOCRACY', FEDERATION = 'FEDERATION', COUNCIL_RULE = 'COUNCIL_RULE', MERITOCRACY = 'MERITOCRACY', COLLECTIVE = 'COLLECTIVE', AUTHORITARIAN_STATE = 'AUTHORITARIAN_STATE', ARCHIVE_GOVERNANCE = 'ARCHIVE_GOVERNANCE' }

export enum EconomyType { RESOURCE_SHARING = 'RESOURCE_SHARING', MARKET_ECONOMY = 'MARKET_ECONOMY', POST_SCARCITY = 'POST_SCARCITY', CENTRALIZED_CONTROL = 'CENTRALIZED_CONTROL', KNOWLEDGE_ECONOMY = 'KNOWLEDGE_ECONOMY' }

export enum CivilizationArchetype { THE_SCHOLARS = 'THE_SCHOLARS', THE_BUILDERS = 'THE_BUILDERS', THE_GUARDIANS = 'THE_GUARDIANS', THE_COLLECTORS = 'THE_COLLECTORS', THE_REFORMERS = 'THE_REFORMERS', THE_EXPANSIONISTS = 'THE_EXPANSIONISTS', THE_ARCHIVISTS = 'THE_ARCHIVISTS', THE_HUMANISTS = 'THE_HUMANISTS', THE_TECHNOCRATS = 'THE_TECHNOCRATS', THE_EMPIRES = 'THE_EMPIRES' }

export enum MemoryArchetype { ACHIEVEMENT = 'ACHIEVEMENT', SACRIFICE = 'SACRIFICE', DISCOVERY = 'DISCOVERY', LEADERSHIP = 'LEADERSHIP', PRESERVATION = 'PRESERVATION', REBELLION = 'REBELLION', INNOVATION = 'INNOVATION', FAILURE = 'FAILURE' }

export enum ArtifactType {
  SCIENTIFIC_REPORT = 'SCIENTIFIC_REPORT', GOVERNMENT_DOCUMENT = 'GOVERNMENT_DOCUMENT',
  PERSONAL_DIARY = 'PERSONAL_DIARY', AUDIO_TRANSCRIPT = 'AUDIO_TRANSCRIPT',
  CULTURAL_RECORD = 'CULTURAL_RECORD', HISTORICAL_ARTICLE = 'HISTORICAL_ARTICLE',
  RESEARCH_PAPER = 'RESEARCH_PAPER', LETTER = 'LETTER',
  PHOTOGRAPH = 'PHOTOGRAPH', RECOVERED_TRANSMISSION = 'RECOVERED_TRANSMISSION',
}

export enum CultureOrientation { COLLECTIVIST = 'COLLECTIVIST', INDIVIDUALIST = 'INDIVIDUALIST', PRESERVATIONIST = 'PRESERVATIONIST', EXPANSIONIST = 'EXPANSIONIST', TRADITIONALIST = 'TRADITIONALIST', EXPERIMENTAL = 'EXPERIMENTAL' }

export enum ScienceLevel { STAGNANT = 'STAGNANT', DEVELOPING = 'DEVELOPING', ADVANCED = 'ADVANCED', TRANSCENDENT = 'TRANSCENDENT' }

export enum MilitaryPosture { MINIMAL = 'MINIMAL', DEFENSIVE = 'DEFENSIVE', EXPANSIONIST = 'EXPANSIONIST', DOMINANT = 'DOMINANT' }

export enum EnvironmentalPolicy { RESTORATION = 'RESTORATION', PRESERVATION = 'PRESERVATION', BALANCED = 'BALANCED', EXPLOITATION = 'EXPLOITATION' }

export enum MediaState { OPEN = 'OPEN', INDEPENDENT = 'INDEPENDENT', CURATED = 'CURATED', CONTROLLED = 'CONTROLLED', PROPAGANDA = 'PROPAGANDA' }
